services:
  server:
    image: syncthing/syncthing:1.27
    hostname: '{{.Node.Hostname}}'
    volumes:
      - /data/syncthing:/var/syncthing
    networks:
      - syncthing
    environment:
      - STGUIAPIKEY=A1B2C3
    deploy:
      mode: global

  controller:
    image: ghcr.io/autotren/docker-swarm-syncthing:main
    hostname: '{{.Node.Hostname}}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - syncthing
    environment:
      - STGUIAPIKEY=A1B2C3
      - ST_SRV_NAME=syncthing_server
      # - SLEEP_SECONDS=30
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager

networks:
  syncthing:
    name: syncthing
    driver: overlay